// Code generated by "stringer -type=PackageStatus"; DO NOT EDIT.

package apt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusInstalled-105]
	_ = x[StatusNotInstalled-110]
}

const (
	_PackageStatus_name_0 = "StatusInstalled"
	_PackageStatus_name_1 = "StatusNotInstalled"
)

func (i PackageStatus) String() string {
	switch {
	case i == 105:
		return _PackageStatus_name_0
	case i == 110:
		return _PackageStatus_name_1
	default:
		return "PackageStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
